# Para SOBREPOR volumes do docker-compose.yml e n√£o usar volumes em  CI assim como ports diferentes

version: '3.8'

services:
  plantshop-postgres-db:    
    volumes: [] 
    ports:
      - "5434:5432"
                
  
  plantshop-pgadmin:    
    volumes: [] 
    ports:
      - "5051:80" 
                