# Para SOBREPOR volumes do docker-compose.yml e n√£o usar em CI


version: '3.8'

services:
  plantshop-postgres-db:
    volumes: [] 
                
  
  plantshop-pgadmin:
    volumes: [] 
                